import { CACHE_TTL_METADATA } from "@nestjs/common";

export const METADATA = {
  USER_ROLES: "USER_ROLES",
  BYK_CACHE_ACTIVE: "QUIZ_CACHE_ACTIVE",
  NESTJS_DEFAULT_CACHE_TTL_METADATA: CACHE_TTL_METADATA,
};
